#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", "lc", or "cp")?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor traning for instance)
# incubator: Carpentries Incubator
carpentry: "nbis"
remote_theme: NBISweden/styles-dm-practices@canvas

# Overall title for pages.
title: "Tools for Reproducible Research"

# Life cycle stage of the lesson
# See this page for more details: https://cdh.carpentries.org/the-lesson-life-cycle.html
# Possible values: "pre-alpha", "alpha", "beta", "stable"
life_cycle: "stable"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
email: "edu.trr@nbis.se"

collections:
  episodes:
    output: true
    permalink: /:path/index.html
  course_settings:
    output: true
    permalink: /:path/index.html

defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: course_settings
    values:
      root: ..
      layout: page

exclude:
  - .gitignore
  - .dockerignore
  - Dockerfile
  - README.md
  - vendor
